apiVersion: v1
kind: Pod
metadata:
  name: flask-app
  labels:
    pod: flask-app
spec:
  containers:
  - name: flask
    image: stratcastor/flask-app:latest
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-lb
spec:
  type: LoadBalancer
  selector:
    pod: flask-app
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 5500
